# Generated by Django 6.0 on 2026-02-08 21:54

import datetime
import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('bill_date', models.DateField(default=datetime.date.today)),
                ('total_labor_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_parts_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Overdue', 'Overdue')], default='Unpaid', max_length=50)),
                ('payment_method', models.CharField(blank=True, choices=[('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Cash', 'Cash'), ('Bank Transfer', 'Bank Transfer'), ('Other', 'Other')], max_length=100, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'bills',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClientEquipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('brand', models.CharField(blank=True, choices=[('Carrier', 'Carrier'), ('Trane', 'Trane'), ('York', 'York'), ('Daikin', 'Daikin'), ('Samsung', 'Samsung'), ('LG', 'LG'), ('McQuay', 'McQuay'), ('Lennox', 'Lennox'), ('Goodman', 'Goodman'), ('Daewoo', 'Daewoo'), ('Mitsubishi Electric', 'Mitsubishi Electric'), ('Hitachi', 'Hitachi'), ('Toshiba', 'Toshiba'), ('Rheem', 'Rheem'), ('Bryant', 'Bryant'), ('Other', 'Other')], max_length=100, null=True)),
                ('equipment_type', models.CharField(blank=True, choices=[('Split Wall Mounted', 'Split Wall Mounted'), ('Multi-Split', 'Multi-Split'), ('Chiller Air Cooled', 'Chiller Air Cooled'), ('Chiller Water Cooled', 'Chiller Water Cooled'), ('Package Unit', 'Package Unit'), ('Fan Coil Unit', 'Fan Coil Unit'), ('Ducted System', 'Ducted System'), ('Window Unit', 'Window Unit'), ('Portable Unit', 'Portable Unit'), ('Central AC System', 'Central AC System'), ('Furnace', 'Furnace'), ('Heat Pump', 'Heat Pump'), ('Ventilation System', 'Ventilation System'), ('Dehumidifier', 'Dehumidifier'), ('Air Purifier', 'Air Purifier'), ('VRF System', 'VRF System'), ('Other', 'Other')], max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('warranty_expiration', models.DateField(blank=True, null=True)),
                ('capacity_btu', models.PositiveIntegerField(blank=True, choices=[(9000, '9,000 BTU'), (12000, '12,000 BTU'), (18000, '18,000 BTU'), (24000, '24,000 BTU'), (30000, '30,000 BTU'), (36000, '36,000 BTU'), (48000, '48,000 BTU'), (60000, '60,000 BTU')], null=True)),
                ('status', models.CharField(choices=[('Operational', 'Operational'), ('Requires Repair', 'Requires Repair'), ('Under Maintenance', 'Under Maintenance'), ('Out of Service', 'Out of Service')], default='Operational', max_length=50)),
                ('equipment_condition', models.CharField(choices=[('New', 'New'), ('Refurbished', 'Refurbished'), ('Used', 'Used'), ('For Parts', 'For Parts')], default='New', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'client_equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('client_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], default='Residential', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'clients',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeInvoices',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_hours_worked', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('employee_hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bonuses', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reimbursements', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Paid', 'Paid'), ('Disputed', 'Disputed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employee_invoices',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=50, unique=True)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('password', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Technician', 'Technician'), ('Operator', 'Operator'), ('Trainer', 'Trainer')], default='Technician', max_length=50)),
                ('employee_hourly_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EquipmentFailures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('failure_category', models.CharField(blank=True, choices=[('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('Refrigeration Cycle', 'Refrigeration Cycle'), ('Control System', 'Control System'), ('Airflow', 'Airflow'), ('Leaks', 'Leaks'), ('Drainage', 'Drainage'), ('Noise/Vibration', 'Noise/Vibration'), ('Other', 'Other')], max_length=100, null=True)),
                ('failure_description', models.CharField(blank=True, max_length=100, null=True)),
                ('detected_date', models.DateField(default=datetime.date.today)),
                ('resolved_date', models.DateField(blank=True, null=True)),
                ('severity', models.CharField(blank=True, choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High'), ('Critical', 'Critical')], max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'equipment_failures',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('service_type', models.CharField(choices=[('Inspection', 'Inspection'), ('Installation', 'Installation'), ('Maintenance', 'Maintenance')], max_length=50)),
                ('lead_type', models.CharField(choices=[('Residential', 'Residential'), ('Commercial', 'Commercial')], default='Residential', max_length=20)),
                ('status', models.CharField(choices=[('New', 'New'), ('Contacted', 'Contacted'), ('Follow-up', 'Follow-up'), ('Scheduled', 'Scheduled'), ('Lost', 'Lost')], default='New', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'leads',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderLaborLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hourly_rate_at_time', models.DecimalField(decimal_places=2, max_digits=10)),
                ('labor_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order_labor_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderPartsUsed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('part_name', models.CharField(max_length=150)),
                ('quantity', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'order_parts_used',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('Inspection', 'Inspection'), ('Installation', 'Installation'), ('Maintenance', 'Maintenance')], default='Inspection', max_length=50)),
                ('service_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=40.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'services',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, choices=[('PM', 'Preventive Maintenance'), ('CM', 'Corrective Maintenance'), ('PdM', 'Predictive Maintenance'), ('INSP', 'Inspection'), ('INST', 'Installation')], max_length=20, null=True)),
                ('pressure_suction', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('temperature_in', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('temperature_out', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('amps_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('voltage_reading', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('scheduled_date', models.DateField()),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('next_work_date', models.DateField(blank=True, null=True)),
                ('total_parts_cost', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('total_labor_cost', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'maintenance_orders',
                'managed': False,
            },
        ),
    ]
